apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-manager-certificate
  namespace: ${namespace}
spec:
  secretName: cert-manager-certificate-secret
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - "*.${dns_zone}"
    - ${dns_zone}
